Models/ErrorViewModel.cs
namespace ShortenIt.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/LinkModel.cs
using System.ComponentModel.DataAnnotations;
namespace ShortenIt.Models;

public class Link
{
    public string? Id { get; set; }
    [Url]
    [Required]
    public string Url { get; set; }

}

Controllers/LinkController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.EntityFrameworkCore;
using ShortenIt.Data;
using ShortenIt.Models;

namespace ShortenIt.Controllers
{
    public class LinkController : Controller
    {
        private readonly LinkContext _context;
        private readonly ILogger _logger;

        public LinkController(LinkContext context, ILogger<LinkController> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string? id)
        {
            if (id is null) return View();
            else
            {
                var link = await _context.Link.FirstOrDefaultAsync(l => l.Id == id);
                return link is null ? NotFound() : Redirect(link.Url);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Id,Url")] Link link)
        {
            if (ModelState.IsValid)
            {
                link.Id = RandomString();
                _context.Add(link);
                await _context.SaveChangesAsync();
                return Redirect($"~/Link/Details/{link.Id}");
            }
            return View();
        }
        string RandomString()
        {
            var random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, 20)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }


        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Link == null)
            {
                return NotFound();
            }

            var link = await _context.Link
                .FirstOrDefaultAsync(m => m.Id == id);
            if (link == null)
            {
                return NotFound();
            }

            ViewBag.url = $"{this.Request.Host}";
            return View(link);
        }

        private bool LinkExists(string id)
        {
            return (_context.Link?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Link/Details.cshtml
@model ShortenIt.Models.Link;

@{
    ViewData["Title"] = "Details";
}

<div class="det">
<h2>@ViewBag.url/Link/Index/@Model.Id</h2>
</div>

Views/Link/Index.cshtml
@model ShortenIt.Models.Link

@{
    ViewData["Title"] = "Index";
}


<form style="display:flex;width:100vw;margin:auto; " asp-controller="Link" asp-action="Index" method="post">
    <input class="SeacrField" asp-for="Url" /> 
    <button class="SeachSubmit" type="submit">Shorten</button>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShortenIt.styles.css" asp-append-version="true" />
</head>
<body>
    <div style = "display:flex;flex-direction:row;margin-left:10px;margin-top:10px;">
        <h1 style="font-size:48px;">S</h1>
        <h2 style="padding-top: 15px;">horten IT</h2>
    </div>
    <div class= "main-container">
        <div class="center-container">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>